### ISSUE TITLE
example Android, iOS app 

### ISSUE THREAD

**Issue by sienikam** [MyPureCloud/genesys-messenger-transport-mobile-sdk#141]
Hello,

is there any example app which demonstrates how to implement basic chat functionalities of connecting to Genesys Cloud Web Messaging ?

**Comment by AfanasievAnton** [comment]
Hi,

If you are looking for UI implementation, then this library does not have any. 
Otherwise, you can check 
[androidComposePrototype](https://github.com/MyPureCloud/genesys-messenger-transport-mobile-sdk/tree/main/androidComposePrototype) - android 
and [iosApp](https://github.com/MyPureCloud/genesys-messenger-transport-mobile-sdk/tree/main/iosApp) - ios. 
We use this applications as our testing/demo apps. 
You are also invited to take a look on our documentation page as well:
https://developer.genesys.cloud/commdigital/digital/webmessaging/messenger-transport-mobile-sdk/
