### ISSUE TITLE
Apple Silicon workaround in 1.2.2 does not play well with SPM

### ISSUE THREAD

**Issue by jalmaas** [MyPureCloud/genesys-messenger-transport-mobile-sdk#93]
The workaround for building to simulator on Apple Silicon-based computers by setting in your podspec `"EXCLUDED_ARCHS[sdk=iphonesimulator*]": "arm64"` does not work for projects also using SPM. Could you create a framework with Arm64 iOS Simulator slice?

**Comment by crumpf** [comment]
@jalmaas Thank you for filing this issue! This will be fixed in the next release of the Pod. The `1.2.2` XCFramework release includes simulator architectures for both arm64 and x86_64. However, as you pointed out, the podspec should not be excluding the arm64 arch. In the interim, a workaround might be to make a local podspec for GenesysCloudMessengerTransport pod based on the currently published podspec and remove the `EXCLUDED_ARCHS` lines. And then you can reference it from your Podfile like:

```
pod 'GenesysCloudMessengerTransport', :podspec => './GenesysCloudMessengerTransport.podspec'
```

We're also looking to make Messenger Transport SDK available through SPM which may also be of future interest to you.

Thanks again for taking the time to bring this to our attention.

**Comment by jalmaas** [comment]
Great! Thanks for the quick reply! That workaround will do while we wait for the updated podspec and maybe SPM-package..?
